spring:
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
    url: ENC(EOKHZqkx7CnYC1T+sLI+T71Y87wLIGz/G7yIrua+evXmBEGw4r/LbxptdFQeW8Ckg8f/4wEgtAFFm9FlStdiMqzSRaFvMn8AqFTD7fcdYNRWWQcIviTGqd1TghTU6971rn3vrZI/UcwuktlK+WaEKg==)
    username: ENC(f+UztJwxp1WJdSFRtE5HyHeE/4wxv3pUXPwmqbjWaB+u2h8ZvOwp1C5Q8hX66dp+)
    password: ENC(JfGO2t5etZQgZsv/vTLTTJIvjwSdGbAQQU0maVWqJuufFmyM0EChESTmoKfvcGTi)

