spring:
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
    url: ENC(B8835o+IG4UGtH96C1Oyz9fA/uoFsYYPVNAcUpALWl8uCak9loMNWdi/5G81aShoQWW9IBDLkcrN/uXni43/hK8kD77p705mq0/nvOVjuKkqKl/IkmFkg4z5hWgCWHcEWq3XtZ+shQo1jwiUT2IQgDpoXKSfmGBLIxVkosJnsio3msH977BZ9Np+MYMQ2p2j)
    username: ENC(7rfbyuidwrAL5DbOml9g8Bg/gNbqatCR7zvUlpT/UgcHEU9uzM7fCsI4sKKtWwP2)
    password: ENC(GTngfGtohcO9saGuH81x8NZw6zhQC4zpG8oJVt5gFBfHqqScYgJOv2Sql8Q5urA5LI/o6pOGW2PDbFwNLZNwkQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


#server:
#  tomcat:
#    threads:
#      max: 5

